// ── BRBC TOURNAMENT DATA (shared mock data for all screens) ──

window.BRBC_DATA = {
  edition: "III",
  year: 2026,
  venue: "Braintree Municipal Golf Course",
  dates: "May 8 – 10, 2026",
  weather: { temp: 68, cond: "Partly Cloudy", wind: "8 mph SW" },

  matches: [
    {
      id: "m1",
      time: "11:00 AM",
      tee: 1,
      thru: 0,
      status: "upcoming",
      rizo:   { players: ["Keane Costa", "Bobby Devin"], score: 0 },
      brooks: { players: ["Lic", "Connor Hooper"],       score: 0 },
      lead: null,
      lead_amt: 0,
    },
    {
      id: "m2",
      time: "11:10 AM",
      tee: 1,
      thru: 0,
      status: "upcoming",
      rizo:   { players: ["Cam Hooper", "John Tomlin"],       score: 0 },
      brooks: { players: ["Reed Pike", "Kevin O'Halloran"],   score: 0 },
      lead: null,
      lead_amt: 0,
    },
    {
      id: "m3",
      time: "11:20 AM",
      tee: 1,
      thru: 0,
      status: "upcoming",
      rizo:   { players: ["Jared Rizo", "Andrew Dion"], score: 0 },
      brooks: { players: ["Sean Brooks", "Kyle Devin"], score: 0 },
      lead: null,
      lead_amt: 0,
    },
    {
      id: "m4",
      time: "11:30 AM",
      tee: 1,
      thru: 0,
      status: "upcoming",
      rizo:   { players: ["Tim Flynn", "Jeff Demers"],          score: 0 },
      brooks: { players: ["Mike Preziosi", "Mark Prezioisi"],   score: 0 },
      lead: null,
      lead_amt: 0,
    },
    {
      id: "m5",
      time: "11:40 AM",
      tee: 1,
      thru: 0,
      status: "upcoming",
      rizo:   { players: ["Billy Gardner", "Kevin Hock"], score: 0 },
      brooks: { players: ["Jay Stasiak", "Jake Harris"],  score: 0 },
      lead: null,
      lead_amt: 0,
    },
  ],

  team_rizo: {
    name: "Rizo",
    captain: "Jared Rizo",
    color: "navy",
    score: 0,
    projected: 0,
    record: { wins: 1, losses: 1 },
    roster: [
      { name: "Jared Rizo",      role: "Captain",      hcp: 6.8,  w: 2, l: 2, h: 2, cups: 1, appearances: 2, bio: "Co-founder and architect of Team Rizo. A balanced 2-2-2 record reflects a captain who plays to win the matches that matter most." },
      { name: "Keane Costa",     role: "Vice Captain", hcp: 4.2,  w: 6, l: 0, h: 0, cups: 1, appearances: 2, bio: "Perfect 6-0-0 across his appearances. The most efficient match play killer in the field." },
      { name: "Cam Hooper",      role: "Player",       hcp: 5.9,  w: 4, l: 0, h: 2, cups: 2, appearances: 2, bio: "Two-time Cup winner with elite consistency. Rarely beats himself and almost never loses." },
      { name: "Tim Flynn",       role: "Player",       hcp: 6.4,  w: 4, l: 2, h: 0, cups: 2, appearances: 2, bio: "Two-time champion with a balanced winning record. The kind of player you want in alternate shot." },
      { name: "Billy Gardner",   role: "Player",       hcp: 8.3,  w: 3, l: 2, h: 1, cups: 1, appearances: 2, bio: "Steady veteran with a 3-2-1 ledger. A captain's pick on any roster." },
      { name: "Andrew Dion",     role: "Player",       hcp: 7.8,  w: 3, l: 0, h: 0, cups: 1, appearances: 1, bio: "Undefeated in his Cup debut (3-0-0). A clear breakout candidate this year." },
      { name: "Nick Radcliffe",  role: "Player",       hcp: 9.1,  w: 3, l: 0, h: 0, cups: 1, appearances: 1, bio: "Burst onto the scene with three straight wins as a rookie. Brings energy and confidence into year two." },
      { name: "Kevin Hock",      role: "Player",       hcp: 11.4, w: 3, l: 3, h: 0, cups: 1, appearances: 2, bio: "Streaky veteran with six matches under his belt. When he's locked in, he's a threat to anyone." },
      { name: "Jeff Demers",     role: "Player",       hcp: 9.6,  w: 3, l: 3, h: 0, cups: 1, appearances: 2, bio: "A reliable match play hand with three wins on his card and the demeanor to back it up." },
      { name: "John Tomlin",     role: "Player",       hcp: 10.7, w: 2, l: 2, h: 2, cups: 1, appearances: 2, bio: "Two appearances and a balanced 2-2-2 record. A foundational locker room piece for Team Rizo." },
      { name: "Chris Flaherty",  role: "Player",       hcp: 12.1, w: 2, l: 3, h: 1, cups: 1, appearances: 2, bio: "Battle-tested veteran with a knack for hanging tough in losing matches." },
      { name: "Bobby Devin",     role: "Player",       hcp: 11.0, w: 2, l: 0, h: 1, cups: 0, appearances: 1, bio: "Strong rookie campaign (2-0-1). The Devin brothers are Cup material." },
      { name: "Brad Carlson",    role: "Player",       hcp: 13.4, w: 1, l: 2, h: 0, cups: 0, appearances: 1, bio: "Rookie campaign brought a 1-2-0 finish. Looking to build on it in year two." },
      { name: "Matt Gardner",    role: "Player",       hcp: 15.3, w: 0, l: 4, h: 2, cups: 0, appearances: 2, bio: "Has yet to lift the Cup but his halves keep him in every match." },
      { name: "Andrew Nazarro",  role: "Player",       hcp: 14.5, w: 0, l: 2, h: 1, cups: 1, appearances: 1, bio: "Cup winner with a half on his card. Adds depth to a deep Rizo rotation." },
      { name: "Mike Rizzo",      role: "Player",       hcp: 16.0, w: 0, l: 3, h: 0, cups: 1, appearances: 1, bio: "Joins the Rizo roster with championship pedigree from his rookie year." },
    ],
  },

  team_brooks: {
    name: "Brooks",
    captain: "Sean Brooks",
    color: "crimson",
    score: 0,
    projected: 0,
    record: { wins: 1, losses: 1 },
    roster: [
      { name: "Sean Brooks",       role: "Captain",      hcp: 7.4,  w: 3, l: 3, h: 0, cups: 1, appearances: 2, bio: "Co-founder of the BRBC and the steady hand at the helm of Team Brooks. A reliable match play presence with a knack for turning halves into wins." },
      { name: "Lic",               role: "Vice Captain", hcp: 4.5,  w: 5, l: 0, h: 1, cups: 2, appearances: 2, bio: "The most dominant player in BRBC history (5-0-1). Fearless on tough holes and rarely loses control of a match." },
      { name: "Reed Pike",         role: "Player",       hcp: 5.8,  w: 4, l: 0, h: 2, cups: 2, appearances: 2, bio: "Two-time Cup winner with one of the cleanest match play resumés in the field. Calm, consistent, and almost impossible to rattle." },
      { name: "Mike Preziosi",     role: "Player",       hcp: 6.2,  w: 4, l: 2, h: 0, cups: 1, appearances: 2, bio: "Steady ball-striker with four wins on his ledger. The kind of player who makes his partner's life easier." },
      { name: "Jay Stasiak",       role: "Player",       hcp: 9.4,  w: 2, l: 2, h: 2, cups: 2, appearances: 2, bio: "Two-time champion who plays an even-keeled brand of golf. As likely to halve a match as to win it." },
      { name: "Kyle Devin",        role: "Player",       hcp: 7.1,  w: 3, l: 0, h: 0, cups: 1, appearances: 1, bio: "Undefeated in his lone Cup appearance (3-0-0). A weapon entering his second go-around." },
      { name: "Nick Ciuffo",       role: "Player",       hcp: 8.6,  w: 3, l: 0, h: 0, cups: 0, appearances: 1, bio: "Burst onto the scene with three straight wins as a rookie. Plays without fear." },
      { name: "Jake Harris",       role: "Player",       hcp: 8.1,  w: 3, l: 3, h: 0, cups: 1, appearances: 2, bio: "Six matches, six learning experiences — Jake's gritty short game keeps him in matches he has no business winning." },
      { name: "Mark Prezioisi",    role: "Player",       hcp: 10.3, w: 2, l: 2, h: 2, cups: 1, appearances: 2, bio: "A steady veteran with a balanced 2-2-2 record. The kind of player who closes you out on 18." },
      { name: "Kevin O'Halloran",  role: "Player",       hcp: 11.5, w: 2, l: 3, h: 1, cups: 1, appearances: 2, bio: "Battle-tested over two appearances. Plays best when the team needs a half." },
      { name: "Sean Williamson",   role: "Player",       hcp: 9.7,  w: 2, l: 0, h: 1, cups: 1, appearances: 1, bio: "Strong rookie debut (2-0-1). Brings a calm presence into the rotation." },
      { name: "Connor Hooper",     role: "Player",       hcp: 8.4,  w: 2, l: 0, h: 1, cups: 0, appearances: 1, bio: "Solid first appearance with two wins. Brother to Cam — and a strong player in his own right." },
      { name: "Jack Wilson",       role: "Player",       hcp: 10.2, w: 2, l: 1, h: 0, cups: 1, appearances: 1, bio: "Won two of three matches in his rookie season. A confidence pick for the captain." },
      { name: "Lou",               role: "Player",       hcp: 14.7, w: 1, l: 5, h: 0, cups: 0, appearances: 2, bio: "A grinder. Has lost more than he's won but is never out of a match." },
      { name: "Bobby Lawton",      role: "Player",       hcp: 16.8, w: 0, l: 5, h: 1, cups: 0, appearances: 2, bio: "The Lawton family flag-bearer. Has yet to find his Cup form but the talent is there." },
      { name: "Joe Hock",          role: "Player",       hcp: 13.2, w: 0, l: 2, h: 1, cups: 0, appearances: 1, bio: "Younger brother to Kevin. Looking to find his first Cup win in his sophomore year." },
    ],
  },

  hall_of_champions: [
    { year: 2025, edition: "II", winner: "Rizo", score: "16 – 8",
      photo: "assets/champ-2025.jpg",
      roster: ["Jared Rizo","Keane Costa","Cam Hooper","Tim Flynn","Billy Gardner","Andrew Dion","Nick Radcliffe","Kevin Hock","Jeff Demers","John Tomlin","Chris Flaherty","Andrew Nazarro","Mike Rizzo","Lic","Reed Pike","Jay Stasiak"] },
    { year: 2024, edition: "I", winner: "Brooks", score: "18.5 – 5.5",
      photo: "assets/champ-2024.jpg",
      roster: ["Sean Brooks","Mike Preziosi","Jake Harris","Mark Prezioisi","Kevin O'Halloran","Sean Williamson","Jack Wilson","Kyle Devin","Lic","Reed Pike","Jay Stasiak","Cam Hooper","Tim Flynn","Lou","Bobby Lawton","Joe Hock"] },
  ],
};
