// ── BRBC TOURNAMENT DATA (shared mock data for all screens) ──

window.BRBC_DATA = {
  edition: "VIII",
  year: 2026,
  venue: "Braintree Municipal Golf Course",
  dates: "May 8 – 10, 2026",
  weather: { temp: 68, cond: "Partly Cloudy", wind: "8 mph SW" },

  matches: [
    {
      id: "m1",
      time: "11:00 AM",
      tee: 1,
      thru: 14,
      status: "live",
      rizo: { players: ["Jake Harris", "Kevin Hock"], score: 1, side: "rizo" },
      brooks: { players: ["Chris Flats", "Mark Prez"], score: 0 },
      lead: "rizo",
      lead_amt: 1,
      front: { winner: "rizo", margin: 1 },
      back:  { winner: "brooks", margin: 1, in_progress: true },
      total: { winner: null, margin: 0, in_progress: true },
      holes: [
        // 0=AS, 1=Rizo, -1=Brooks
        { n:1, par:4, dist:402, win:1 },
        { n:2, par:5, dist:521, win:0 },
        { n:3, par:3, dist:174, win:1 },
        { n:4, par:4, dist:388, win:-1 },
        { n:5, par:4, dist:425, win:1 },
        { n:6, par:4, dist:411, win:0 },
        { n:7, par:3, dist:198, win:1 },
        { n:8, par:5, dist:548, win:-1 },
        { n:9, par:4, dist:436, win:0 },
        { n:10, par:4, dist:392, win:0 },
        { n:11, par:4, dist:445, win:-1 },
        { n:12, par:3, dist:165, win:1 },
        { n:13, par:5, dist:512, win:-1 },
        { n:14, par:4, dist:418, win:-1 },
      ],
    },
    {
      id: "m2",
      time: "11:10 AM",
      tee: 1,
      thru: 13,
      status: "live",
      rizo: { players: ["Dan Stone", "Pat Salas"], score: 0 },
      brooks: { players: ["John Morgan", "Tyler Jones"], score: 0 },
      lead: null,
      lead_amt: 0,
      front: { winner: "halved", margin: 0 },
      back:  { winner: null, margin: 0, in_progress: true },
      total: { winner: null, margin: 0, in_progress: true },
      holes: [
        { n:1, par:4, dist:402, win:0 },
        { n:2, par:5, dist:521, win:1 },
        { n:3, par:3, dist:174, win:-1 },
        { n:4, par:4, dist:388, win:0 },
        { n:5, par:4, dist:425, win:1 },
        { n:6, par:4, dist:411, win:-1 },
        { n:7, par:3, dist:198, win:0 },
        { n:8, par:5, dist:548, win:0 },
        { n:9, par:4, dist:436, win:0 },
        { n:10, par:4, dist:392, win:1 },
        { n:11, par:4, dist:445, win:-1 },
        { n:12, par:3, dist:165, win:0 },
        { n:13, par:5, dist:512, win:0 },
      ],
    },
    {
      id: "m3",
      time: "11:20 AM",
      tee: 1,
      thru: 11,
      status: "live",
      rizo: { players: ["Greg Rizo", "Mike Smith"], score: 2, side: "rizo" },
      brooks: { players: ["Justin Brooks", "Pete Brown"], score: 0 },
      lead: "rizo",
      lead_amt: 2,
      front: { winner: "rizo", margin: 2 },
      back:  { winner: "rizo", margin: 1, in_progress: true },
      total: { winner: null, margin: 0, in_progress: true },
      holes: [
        { n:1, par:4, dist:402, win:1 },
        { n:2, par:5, dist:521, win:0 },
        { n:3, par:3, dist:174, win:1 },
        { n:4, par:4, dist:388, win:1 },
        { n:5, par:4, dist:425, win:0 },
        { n:6, par:4, dist:411, win:-1 },
        { n:7, par:3, dist:198, win:1 },
        { n:8, par:5, dist:548, win:0 },
        { n:9, par:4, dist:436, win:0 },
        { n:10, par:4, dist:392, win:1 },
        { n:11, par:4, dist:445, win:0 },
      ],
    },
    {
      id: "m4",
      time: "11:30 AM",
      tee: 1,
      thru: 0,
      status: "upcoming",
      rizo: { players: ["Tom Vega", "Sean Murphy"], score: 0 },
      brooks: { players: ["Drew Cole", "Ben Park"], score: 0 },
      lead: null,
      lead_amt: 0,
    },
    {
      id: "m5",
      time: "11:40 AM",
      tee: 1,
      thru: 0,
      status: "upcoming",
      rizo: { players: ["Will Hayes", "Sam Reed"], score: 0 },
      brooks: { players: ["Nate Doyle", "Owen Yu"], score: 0 },
      lead: null,
      lead_amt: 0,
    },
  ],

  team_rizo: {
    name: "Rizo",
    captain: "Greg Rizo",
    color: "navy",
    score: 4,
    projected: 8.7,
    record: { wins: 4, losses: 3 },
    roster: [
      { name: "Greg Rizo",    role: "Captain",      hcp: 6.2,  w: 14, l: 9,  h: 2, cups: 1, bio: "The architect of Team Rizo and the tournament's founding father. A savvy course manager who rarely beats himself, Greg controls matches through placement and patience. Dangerous from tee to green and a reliable partner in any format — his leadership on and off the course is the backbone of the Rizo dynasty." },
      { name: "Jake Harris",  role: "Vice Captain", hcp: 8.1,  w: 9,  l: 7,  h: 1, cups: 1, bio: "A gritty competitor who plays his best golf when the pressure is highest. Jake's short game is among the sharpest in the field, and he has a knack for stealing halves on holes he has no business winning. A veteran of the biggest moments in BRBC history." },
      { name: "Kevin Hock",   role: "Player",       hcp: 11.4, w: 6,  l: 8,  h: 2, cups: 1, bio: "Streaky and entertaining, Kevin can look like the best player on the course for six holes and then self-destruct at the worst possible moment. When he's locked in, he's a genuine threat to anybody in the field. The team's most unpredictable wildcard." },
      { name: "Dan Stone",    role: "Player",       hcp: 4.8,  w: 11, l: 5,  h: 3, cups: 1, bio: "The statistical standout of Team Rizo. Dan's low handicap is earned — he hits it long, misses in the right spots, and makes just enough putts to keep opponents on edge. One of the most consistent performers in BRBC history across both formats." },
      { name: "Pat Salas",    role: "Player",       hcp: 9.2,  w: 7,  l: 6,  h: 1, cups: 1, bio: "A steady presence who thrives in alternate shot formats. Pat's controlled ball-striking and level head make him a reliable partner, and his match play record reflects a player who rarely implodes. Not flashy, but consistently dangerous." },
      { name: "Mike Smith",   role: "Player",       hcp: 13.7, w: 4,  l: 9,  h: 2, cups: 1, bio: "The heart of the locker room, Mike plays with relentless enthusiasm regardless of the score. His record doesn't tell the whole story — he's been competitive in most matches and always makes for an entertaining round. Still hunting his best performance on the big stage." },
      { name: "Tom Vega",     role: "Player",       hcp: 7.5,  w: 8,  l: 6,  h: 0, cups: 0, bio: "A clean striker with a reliable iron game and zero halves to his name — Tom plays to win every hole. His aggressive style can backfire on tough tracks but makes him electric to watch when the game is on. A player opponents never take lightly." },
      { name: "Sean Murphy",  role: "Player",       hcp: 10.3, w: 5,  l: 7,  h: 2, cups: 0, bio: "Quietly improving year over year. Sean's ball-striking has tightened considerably and his course management has grown with experience. He's capable of knocking off higher-ranked opponents on a good day, and those days are coming more frequently." },
      { name: "Will Hayes",   role: "Player",       hcp: 6.9,  w: 9,  l: 4,  h: 1, cups: 0, bio: "One of the best win percentages in the field despite never lifting the Cup. Will is a fundamentally sound player with a composed demeanor under pressure. His iron play is a weapon, and his record suggests he's due for a breakout Cup performance." },
      { name: "Sam Reed",     role: "Rookie",       hcp: 12.1, w: 0,  l: 0,  h: 0, cups: 0, bio: "The newcomer to the BRBC stage. Sam arrives with a solid amateur background and a game that should translate well to match play. No Cup record to speak of yet, but first impressions on the big stage have been promising. One to watch." },
    ],
  },

  team_brooks: {
    name: "Brooks",
    captain: "Justin Brooks",
    color: "crimson",
    score: 1,
    projected: 3.8,
    record: { wins: 3, losses: 4 },
    roster: [
      { name: "Justin Brooks", role: "Captain",      hcp: 5.4,  w: 13, l: 10, h: 3, cups: 1, bio: "The co-founder and fiercest rival to the Rizo camp. Justin brings an elite competitive IQ and a ball-striking game that holds up under any conditions. As captain he sets the tone — demanding, detail-oriented, and always looking for the edge. The BRBC simply wouldn't exist without him." },
      { name: "Chris Flats",   role: "Vice Captain", hcp: 7.8,  w: 10, l: 8,  h: 2, cups: 1, bio: "The most decorated Vice Captain in BRBC history. Chris plays an aggressive brand of golf that forces opponents into defensive decisions. His short game around the greens is excellent and his composure in tight matches is unmatched on the Brooks side of the ledger." },
      { name: "Mark Prez",     role: "Player",       hcp: 12.1, w: 5,  l: 9,  h: 1, cups: 1, bio: "A fan favourite whose scoreboard presence belies his impact on team morale. Mark has a flair for the dramatic hole, capable of hitting shots that shift the momentum of an entire session. His record is improving and his best golf may still be ahead of him." },
      { name: "John Morgan",   role: "Player",       hcp: 5.2,  w: 12, l: 6,  h: 2, cups: 1, bio: "Arguably the most technically gifted player in the entire field. John's low handicap is backed by a ball-striking game that draws envious looks from all sides. His win percentage is among the top in BRBC history and he remains a constant threat across all formats." },
      { name: "Tyler Jones",   role: "Player",       hcp: 9.6,  w: 7,  l: 7,  h: 1, cups: 1, bio: "Exactly .500 on the all-time record and proud of it. Tyler is a grinder who refuses to concede a hole, making him particularly effective in close matches that come down to the wire. Never out of a game, always in your head." },
      { name: "Pete Brown",    role: "Player",       hcp: 14.3, w: 3,  l: 10, h: 2, cups: 1, bio: "A Cup winner who defies his record. Pete's best attribute is that opponents consistently underestimate him — and then regret it. He plays loose, plays fast, and occasionally pulls out rounds that leave the entire field speechless. A genuine dark horse every time out." },
      { name: "Drew Cole",     role: "Player",       hcp: 8.4,  w: 8,  l: 7,  h: 0, cups: 0, bio: "Drew does not halve holes. His all-or-nothing approach produces some of the tournament's most memorable swings — in both directions. His handicap is trending in the right direction and his zero halves signals a player who always backs himself on the 18th." },
      { name: "Ben Park",      role: "Player",       hcp: 11.0, w: 6,  l: 8,  h: 2, cups: 0, bio: "A steady middle-of-the-roster contributor who has quietly improved his record each year. Ben's approach play is his strongest asset, and he's at his best when opponents try to overpower a course that demands precision over length." },
      { name: "Nate Doyle",    role: "Player",       hcp: 7.2,  w: 9,  l: 5,  h: 1, cups: 0, bio: "One of Team Brooks' most reliable performers and a strong cup-run contender. Nate's combination of length off the tee and a tidy short game makes him a complete player. His record suggests he can compete with anyone in the field when his game is on." },
      { name: "Owen Yu",       role: "Rookie",       hcp: 13.5, w: 0,  l: 0,  h: 0, cups: 0, bio: "The wild card entry on the Brooks side. Owen is a new face whose game is still being assessed at this level, but early signs in practice suggest a player with genuine ball-striking talent. The match play format suits first-timers — anything can happen hole by hole." },
    ],
  },

  hall_of_champions: [
    { year: 2025, edition: "II", winner: "Rizo", score: "16 – 8",
      photo: "assets/champ-2025.jpg",
      roster: ["Greg Rizo","Mike Smith","Jake Harris","Kevin Hock","Dan Stone","Pat Salas","Anthony Licciardello","Kyle Devin","Mike Rizzo","John Tomlin","Jack Wilson","Jared Rizo","Jay Stasiak","Reed Pike","Billy Gardner","Andrew Nazarro"] },
    { year: 2024, edition: "I", winner: "Brooks", score: "18.5 – 2.5",
      photo: "assets/champ-2024.jpg",
      roster: ["Justin Brooks","Chris Flats","John Morgan","Pete Brown","Mark Prez","Tyler Jones"] },
  ],
};
